#!/bin/bash

# 1. Remove all symbolic links
rm -rf ~/.vim/vimrc ~/.vimrc
rm -rf ~/.vim/vimrc.mappings ~/.vimrc.mappings
rm -rf ~/.vim/vimrc.plugins ~/.vimrc.plugins
rm -rf ~/.vim/vimrc.plugins.conf ~/.vimrc.plugins.conf

# 2. Remove the .vim folder
rm -rf ~/.vim
